include:
- project: "common/gitlab-helper"
  ref: master
  file: "ci-helper.yml"

workflow: !reference [ .common, workflow ]

variables:
  PKG_NAME: "klepto"

stages:
- build
- test
- deploy

build-klepto:
  before_script:
  - sudo pacman -Syu --noconfirm
  - git config --global --add safe.directory /builds/arch/klepto
  extends: .arch-build
  image: ${CI_REGISTRY}/common/gitlab-helper/archlinux-yay:master
  needs: []
  
test-klepto:
  extends: .arch-test
  image: ${CI_REGISTRY}/common/gitlab-helper/archlinux-yay:master
  needs: ["build-klepto"]

deploy-klepto:
  extends: .arch-deploy
