name: SyncGithub
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Update
        run: $HOME/arch/update

      - name: Sync Github with AUR
        run: $HOME/arch/syncgithub

