name: UpdateAUR
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Update
        run: $HOME/arch/update

      - name: Update AUR
        run: $HOME/arch/updateaur

